version: "3.4"

services:
  telegraf:
    image: telegraf
    networks:
      - tick-net
    environment:
      - ENGINE_HOST={{.Node.Hostname}}
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
      - /dev/vchiq:/dev/vchiq:ro
      - /opt/vc:/opt/vc:ro
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    deploy:
      restart_policy:
        condition: on-failure
      mode: global

  influxdb:
    image: influxdb:1.2
    networks:
      - tick-net
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - tick-net
      - traefik
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=snuids-radar-panel,neocat-cal-heatmap-panel,petrslavotinek-carpetplot-panel
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.domain=${MAIN_DOMAIN}"
        - "traefik.docker.network=traefik"
        - "traefik.backend=grafana"
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:grafana.${MAIN_DOMAIN}"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"

  chronograf:
    image: chronograf:1.3
    networks:
      - tick-net
      - traefik
    ports:
      - 8888:8888
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.domain=${MAIN_DOMAIN}"
        - "traefik.docker.network=traefik"
        - "traefik.backend=chronograf"
        - "traefik.port=8888"
        - "traefik.frontend.auth.basic=true"
        - "traefik.frontend.auth.basic=${AUTH_CHRONOGRAF_USER}:${AUTH_CHRONOGRAF_PASSWORD}"
        - "traefik.frontend.rule=Host:chronograf.${MAIN_DOMAIN}"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"

  kapacitor:
    image: kapacitor:1.2
    networks:
      - tick-net
    configs:
      - source: kapacitor-config
        target: /etc/kapacitor/kapacitor.conf
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

configs:
  telegraf-config:
    file: $PWD/conf/telegraf/telegraf.conf
  kapacitor-config:
    file: $PWD/conf/kapacitor/kapacitor.conf

networks:
  tick-net:
    driver: overlay
  traefik:
    driver: overlay
    external: true

volumes:
    grafana: {}
