version: '3.4'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.domain=${MAIN_DOMAIN}"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:portainer.${MAIN_DOMAIN}"
        - "traefik.port=9000"
        - "traefik.backend=portainer"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik:
    driver: overlay
    external: true

volumes:
  portainer_data:
